api/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [

    # re_path("^get/o/(?P<owner_key>.+)$", views.get_data, name="api_get_ok", kwargs={"foo": "bar"}),
    path("get/fb/<slug:owner_key>", views.get_data, name="api_get_fb", kwargs={"mode": "fb"}),
    path("get/ann/<slug:owner_key>", views.get_data, name="api_get_ann", kwargs={"mode": "ann"}),
    re_path("get/?", views.get_data, name="api_get"),
    re_path("add/?", views.add_data, name="api_add"),

]

base/urls.py
from django.urls import path

from . import views
from api import views as api_views


main_view = views.SimpleFeedbackMainView.as_view

urlpatterns = [
    path("", main_view(), name="landingpage"),
    path("new", main_view(), name="newdocumentpage", kwargs={"mode": "new"}),
    path("doc/<slug:slug>/<slug:doc_key>", main_view(), name="reviewpage", kwargs={"mode": "review"}),
    path("doc/<slug:slug>/<slug:doc_key>/done", main_view(), name="review_finished_page", kwargs={"mode": "review_finished"}),
    path("doc/<slug:slug>/<slug:doc_key>/o/<slug:owner_key>", main_view(), name="documentpage", kwargs={"mode": "owner"}),
    path("debug", main_view(), name="debugpage", kwargs={"mode": "debug"}),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("base.urls")),
]

base/models.py
from django.db import models
import secrets

# for the sake of reduced complexity we implement our own serialize methods here
# this should be professionallized in the future

class Document(models.Model):
    slug = models.SlugField(max_length=500, blank=False, null=False)
    owner_key = models.SlugField(max_length=20, blank=False, null=False)
    doc_key = models.SlugField(max_length=20, blank=False, null=False)
    content = models.TextField()
    comment_for_reviewers = models.TextField(blank=True)
    render_markdown = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # secrets.token_hex(3) -> 3 Bytes give 6 Chars
        self.doc_key = secrets.token_hex(3)[:5]
        self.owner_key = secrets.token_hex(5)
        super().save(*args, **kwargs)

    def serialize(self):
        res = {
            "pk": self.pk,
            "_type": str(type(self)),
            "slug": self.slug,
            "owner_key": self.owner_key,
            "doc_key": self.doc_key,
            "content": self.content,
            "comment_for_reviewers": self.comment_for_reviewers,
            "render_markdown": self.render_markdown,
        }
        return res


class Feedback(models.Model):
    reviewer = models.CharField(max_length=250, blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)
    document = models.ForeignKey(Document, on_delete=models.CASCADE, null=False, related_name="feedbacks")

    def serialize(self, ann_list=True):
        """
        return the object as as serializable dict
        """
        res = {
            "pk": self.pk,
            "_type": str(type(self)),
            "reviewer": self.reviewer,
            "date": self.date.strftime('%Y-%m-%d %H:%M:%S'),
            "document": self.document.serialize(),
        }
        if ann_list:
            # access related manager (reverse of foreign key relation below)
            res["annotation_list"] = [ann.serialize() for ann in self.annotations.all()]

        return res


# taken from https://github.com/acdh-oeaw/django-recogito
class RecogitoAnnotation(models.Model):
    re_id = models.CharField(max_length=100, primary_key=True)
    re_text = models.TextField(blank=True, null=True)
    re_start = models.IntegerField(blank=True, null=True)
    re_end = models.IntegerField(blank=True, null=True)
    re_payload = models.JSONField(blank=True, null=True)
    re_app = models.CharField(max_length=100, blank=True, null=True)
    re_model = models.CharField(max_length=100, blank=True, null=True)
    re_object_id = models.CharField(max_length=100, blank=True, null=True)
    re_field_name = models.CharField(max_length=100, blank=True, null=True)

    # this allows to access all related RecogitoAnnotaion objects via `feedback.annoations` (related Manager)
    re_feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE, null=False, related_name="annotations")

    def __str__(self):
        return f"{self.re_text} ({self.re_id})"

    def serialize(self):
        """
        The JS API expects a specific data structure (schema) which is different from what it provides
        when the data is sent. This method transforms the data into that expected structure.
        """
        res = {
            "pk": self.pk,
            "_type": str(type(self)),
            "start": self.re_start,
            "end": self.re_end,
            "text": self.re_text, # target text
            "comment_value": self.re_payload["body"][0]["value"],
            # save a reference to the feedback but without annotation list (prevent inifinite reference circle)
            "feedback": self.re_feedback.serialize(ann_list=False)
        }
        return res

    def save(self, *args, **kwargs):
        if self.re_payload:
            data = self.re_payload
            target = data['target']['selector']
            for y in target:
                if 'start' in y.keys():
                    self.re_start = y['start']
                    self.re_end = y['end']
                else:
                    self.re_text = y['exact']
        super().save(*args, **kwargs)

base/views.py
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.forms import ModelForm
from .models import Document
from .simple_pages_interface import get_sp

# Create your views here.

class SimpleFeedbackMainView(View):
    def get(self, request, slug=None, doc_key=None, owner_key=None, mode=None, doc_pk=None):
        context = {
            # having a nested dict for easier debugging in the template
            "data": {
                "slug": slug,
                "doc_key": doc_key,
                "owner_key": owner_key,
                "mode": mode,
                "sp": None
            }
        }

        if mode == "new":
            template = "base/doc_new.html"
            self._new_doc(context)
        elif mode == "new_preview":
            template = "base/doc_new.html"
            self._new_doc(context, doc_pk=doc_pk, owner_key=owner_key)
        elif mode == "review":
            self._set_doc(context, doc_key=doc_key)
            template = "base/doc_review.html"
        elif mode == "review_finished":
            self._set_doc(context, doc_key=doc_key)
            template = "base/doc_review_finished.html"
        elif mode == "owner":
            self._set_doc(context, doc_key=doc_key, owner_key=owner_key)
            template = "base/doc_owner.html"
        elif mode == "debug":
            template = "base/main_old.html"
        else:
            context["data"]["sp"] = get_sp("landing")
            template = "base/main_simplepage.html"

        return render(request, template, context)

    def post(self, request, **kwargs):
        form = DocumentForm(request.POST)
        doc: Document = form.save()
        # from ipydex import IPS; IPS()
        if request.POST.get("action") == "save":
            assert doc.doc_key
            assert doc.owner_key
            url = reverse("documentpage", kwargs={"slug": doc.slug, "doc_key": doc.doc_key, "owner_key": doc.owner_key})
            return HttpResponseRedirect(url)

        return self.get(request, mode="new_preview", doc_pk=doc.pk, owner_key=doc.owner_key)

    def _new_doc(self, context, owner_key=None, doc_pk=None):
        if doc_pk is None:
            context["data"]["formset"] = DocumentForm()
            return

        doc = self._set_doc(context, doc_pk=doc_pk, owner_key=owner_key)
        context["data"]["formset"] = DocumentForm(instance=doc)

    def _set_doc(self, context, doc_pk=None, doc_key=None, owner_key=None):

        assert (doc_pk, doc_key).count(None) == 1

        if doc_pk is not None:
            doc = get_object_or_404(Document, pk=doc_pk)
        elif doc_key is not None:
            doc = get_object_or_404(Document, doc_key=doc_key)
        else:
            assert False  # cannot happen due to test above

        if owner_key is not None:
            if (doc.owner_key != owner_key):
                # TODO: use different exception here
                raise KeyError("owner key does not match")
            doc.owner_mode = True

            # get reviews for this document
            doc.review_nbr = len(doc.feedbacks.all())
        context["data"]["doc"] = doc
        return doc


class DocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = ["slug", "content", "comment_for_reviewers", "render_markdown"]

base/templates/base/base.html
<!DOCTYPE html>
{% load static %}
{#{% load extra_filters %}#}

<html>
<head lang="en">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />

<!--  prevent favicon -->
<link rel="icon" href="data:,">

<link type="text/css" rel="stylesheet" href="{% static 'base.css' %}">


<title>{% block title %}simplefeedback – get comments on your text{% endblock %}</title>

{# the following block allows templates to load scripts e.g. for mathjax #}
{% block head_extension %}{% endblock %}

</head>
<body>

<div class="headerbar">
    <div class="header">
        <a href="{% url 'landingpage'%}" style="text-decoration: none;">
            <div id="header1" class="box-frame">
<div class="boxed">s</div> <div class="boxed">i</div> <div class="boxed">m</div> <div class="boxed">p</div> <div class="boxed">l</div> <div class="boxed">e</div> <div class="boxed">f</div> <div class="boxed">e</div> <div class="boxed">e</div> <div class="boxed">d</div> <div class="boxed">b</div> <div class="boxed">a</div> <div class="boxed">c</div> <div class="boxed">k</div>             </div>
        </a>
            <div id="header2">
                – gather comments for your text
            </div>
    </div> <!-- end of header -->
{% block header_warning %}
{% endblock %}
</div> <!-- end of headerbar -->

<div id="outer-container">

{# `utc` means "unit test comment". This is a simple mechanism to be able to test if the desired content actually was delivered #}
<!--utc_landing_page-->



<div id="id_main" class="{% block main_class %}main{% endblock %}">
{% block content %}

add content

{% endblock %}
</div>

<!-- <div id="vertical-spacer"></div> -->
</div> <!-- end of outer container -->
{% block footer %}
<!-- <footer> -->

<div class="footer">
<div class="footerbar">
    <div class="footer-content">
        {#<a href="{% url 'about' %}">about markpad</a> |#}
        {#<a href="{% url 'legal-notice' %}">legal notice</a> |#}
        ... made with <a href="https://www.djangoproject.com">django</a> and
        <a href="https://django-bleach.readthedocs.io">django-bleach</a> |
        hosted on <a href="https://uberspace.de/">uberspace</a>
        <br>
        {# last deployment: {{"foobar"|get_last_deployment}}. #}
    </div>
</div>
</div>
<!-- </footer> -->
{% endblock %}

{% block main_script %}
foo
{% endblock %}
</body>

</html>

base/templates/base/doc_new.html
{% extends "base/base.html" %}
{% load bleach_tags %}
{% load extra_filters %}


{% block content %}
    {# debug: {{data}} #}
    {% if data.doc %}
        <!--utc_doc_new_preview-->
        <h1 id="h1x">Check Preview</h1>
        <div class="frame-title">URL including slug and review key:</div>
        <div class="preview-frame"><span class="slug-preview">{% url 'reviewpage' data.doc.slug data.doc.doc_key %}</span></div>

        <div class="frame-title">Comment for Reviewers:</div>
        <div class="preview-frame">
            {% if data.doc.comment_for_reviewers %}
            {{data.doc.comment_for_reviewers|render_markdown|bleach}}</span>
            {% else %}
            <div class="placeholder">&lt;No comment provided&gt;</div>
            {% endif %}
        </div>
        <div class="frame-title">Document:</div>
        <div class="preview-frame">
            {% include "base/partial/doc_content.html" with data=data only %}
        </div>
    {% else %}
        <!--utc_doc_new_create-->
        <h1 id="h1x">Create New Document</h1>
    {% endif %}
    {% if data.formset %}
        <form method="post" action="">
            {% csrf_token %}

            <br>
            {% if data.doc %}<div class="frame-title">Edit slug:</div>{% endif %}
            <div><input class="form_input_fw" type="text" name="slug" maxlength="500" required id="id_slug" value="{{data.doc.slug}}" placeholder="document slug" title="document slug"></div>
            <br>

            {% if data.doc %}<div class="frame-title">Edit comment for reviewers:</div>{% endif %}
            <div><textarea class="form_input_fw" name="comment_for_reviewers" rows="5" id="comment_for_reviewers" placeholder="Enter your comment for the reviewers here as markdown text here" title="comment for reviewers">{{data.doc.comment_for_reviewers}}</textarea></div>
            <br>

            {% if data.doc %}<div class="frame-title">Edit document:</div>{% endif %}
            <div><textarea class="form_input_fw" name="content" rows="10" required id="id_content" placeholder="Enter your (markdown) text here" title="document content">{{data.doc.content}}</textarea></div>
            <div><input type="checkbox" class="" id="render_markdown" name="render_markdown" {% if data.doc is None or data.doc.render_markdown %}checked{% endif %} value="True"> Render Markdown</div>

            {% if data.doc %}
            <!--utc_doc_new_save_button-->
            <button style="float: right; margin-left: 1em;" class="btn btn-primary" name="action" value="save" type="submit">save</button>
        {% endif %}
        <button style="float: right;" class="btn btn-primary" name="action" value="preview" type="submit">preview</button>
        </form>
    {% endif %}
{% endblock %}

base/templates/base/doc_owner.html
{% extends "base/base.html" %}
{% load static %}

{% block main_class %}main main_two_column{% endblock %}

{% block content %}
<!--utc_doc_owner-->
    {#debug: {{data}}#}
    {#doc: {{data}}#}

    <!-- needed for unittests: -->
    {{ data.doc.doc_key|json_script:"doc_key" }}
    {{ data.doc.owner_key|json_script:"owner_key" }}

{% if data.doc.owner_mode %}
{{ data.doc.doc_key|json_script:"doc_key" }}
{{ data.doc.owner_key|json_script:"owner_key" }}

{{ data.doc.review_nbr|json_script:"review_nbr" }}

<div class="two_col_container">
<div class="left-column">


    <h2 id="h1x">Owner View ({{data.doc.slug}})</h2>
    <details>
        <summary>
            Review URL: <a href="{% url 'reviewpage' data.doc.slug data.doc.doc_key %}">{% url 'reviewpage' data.doc.slug data.doc.doc_key %}</a>
        </summary>

        <div>Owner URL: <a href="{% url 'documentpage' data.doc.slug data.doc.doc_key data.doc.owner_key %}">{% url 'documentpage' data.doc.slug data.doc.doc_key data.doc.owner_key %}</a></div>

        <div>Slug: <span class="slug-preview">{{data.doc.slug}}</span></div>
        <div>Submitted Reviews: {{data.doc.review_nbr}}</div>

            {% include "base/partial/comment_for_reviewers.html" with data=data only %}
        </details>

    <hr style="margin: 1em 0 3em 0;">
    {% include "base/partial/doc_content.html" with data=data class="show_annotations_content" only %}
    <hr style="margin-bottom: 3em;">

</div> <!-- end of left column -->
<div class="right-column">

    {% if data.doc.review_nbr %}

    <div class="right-column-headline-container">
        <h2>Review Details</h2>
        <div class="prev-next-button-container button">
          <button class="arrow-button" id="btn-activate-prev-ann"> <i class="arrow arrow-left"></i> Prev</button>
          <button class="arrow-button" id="btn-activate-next-ann">Next  <i class="arrow arrow-right"></i></button>
        </div>
      </div>

    <div class="frame-title">Meta data:</div>
    <div class="preview-frame" id="review-detail-meta">&nbsp;
    </div>

    <br>
    Content: <div id="review-detail-content"><span class="placeholder">No comment selected</span></div>
    {% else %}
    <br><br><br>
    <div class="placeholder">No review yet available</div>
    {% endif %}

</div> <!-- end of right column -->


</div><!-- end of two column container -->
{% else %}
    {# This normally should never be displayed and is a second layer of security #}
    Wrong owner key
{% endif %} {#end of if data.doc.owner_mode#}
{% endblock %}


{% block main_script %}
<script type="text/javascript" src="{% static 'recogito/recogito.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<!-- <script src="{% static 'simplefeedback.js' %}"></script> -->
<script src="{% static 'Highlighter.js' %}"></script>
<script src="{% static 'showfeedback.js' %}"></script>
{% endblock %}

base/templates/base/doc_review.html
{% extends "base/base.html" %}
{% load static %}
{% load extra_filters %}
{% load bleach_tags %}

{% block head_extension %}
<link href="{% static 'recogito/recogito.min.css' %}" rel="stylesheet">
{% endblock%}


{% block content %}
<!--utc_doc_review-->
    {#debug: {{data}}#}
    {#doc: {{data.doc}}#}

    {{ data.doc.doc_key|json_script:"doc_key" }}

    <h1 id="h1x">Review Document</h1>
    <div>Slug: <span class="slug-preview">{{data.slug}}</span></div>

    {% include "base/partial/comment_for_reviewers.html" with data=data only %}

    <hr style="margin: 3em 0 3em 0;">

    <form id="reviewForm">
        <div><input class="form_input_fw" type="text" name="reviewer" maxlength="500" required id="reviewerName" placeholder="reviewer name" title="reviewer name"></div>
        <hr>
        {% include "base/partial/doc_content.html" with data=data only %}

        <button id="mainSubmit" style="float: right; margin-left: 1em;" class="btn btn-primary" type="submit">submit feedback</button>

    </form>
    <hr style="margin: 3em 0 3em 0;">



{% endblock %}


{% block main_script %}
<script type="text/javascript" src="{% static 'recogito/recogito.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script src="{% static 'simplefeedback.js' %}"></script>
{% endblock %}

base/templates/base/doc_review_finished.html
{% extends "base/base.html" %}
{% load static %}
{% load extra_filters %}
{% load bleach_tags %}



{% block content %}
<!--utc_doc_review-->
    {#debug: {{data}}#}
    {#doc: {{data.doc}}#}

    {{ data.doc.doc_key|json_script:"doc_key" }}

    <h1 id="h1x">Review Finished Successfully</h1>
    <div>Thank you.</div>

{% endblock %}

base/templates/base/error_page.html
{% extends "mainapp/base.html" %}
{% load extra_filters %}
{% load bleach_tags %}



{% block title %}markpad – error{% endblock %}




{% block content %}

<!--utc_error_page-->

<div class="error">

{{ctn.prefix|render_markdown|bleach}} {{ctn.err_msg|render_markdown|bleach}}

</div>

{% endblock %}

base/templates/base/main.html
{% extends "base/base.html" %}

base/templates/base/main_old.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <link href="{% static 'recogito/recogito.min.css' %}" rel="stylesheet">


</head>
<body>

<div class="jumbotron text-center">
  <h1>Example Review</h1>
</div>

<div>
  debug: {{data}}
</div>

<div class="container">

{% if data.formset %}
  <form method="post" action="">
    {% csrf_token %}
    {{data.formset.as_div}}
    <input type="submit" value="Submit Form"/>
  </form>
{% endif %}

    <form id="reviewForm">
            <div class="form-group row" style="margin-bottom: 2em;">
                <!-- <label for="reviewerName" class="col-sm-2 col-form-label">Name</label> -->
                <div class="col-sm-8 offset-sm-2">
                    <input type="text" class="form-control" id="reviewerName" placeholder="Reviewer name">
                </div>

                <div class="col-sm-2">
                    <button id="mainSubmit" type="button" class="btn btn-primary">Submit</button>
                </div>
            </div>

    </form>

    <div id="annotation_content">
        Lorem ipsum dolor sit amet, <span id="click-target1">consectetur</span> adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>

</div>

<script type="text/javascript" src="{% static 'recogito/recogito.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script src="{% static 'simplefeedback.js' %}"></script>

</body>
</html>

base/templates/base/main_simplepage.html
{% extends "base/base.html" %}
{% load bleach_tags %}
{% load extra_filters %}


{% block title %}{{data.sp.title}}: {{ block.super }}{% endblock %}

{% block content %}


<div>{{data.sp.content|render_markdown|bleach}}</div>

{% endblock %}

base/templates/base/md_preview.html
{% extends "mainapp/base.html" %}
{% load extra_filters %}
{% load bleach_tags %}



{% block title %}simple markdown preview{% endblock %}

{% block scripts %}
<!--<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>-->

{% if ctn.enable_mathjax %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML-full"></script>

<!-- source2: https://github.com/mitya57/python-markdown-math  -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"]
});
</script>
{% endif %}
{% endblock %}


{% block header_warning %}
<div class="headerbar-warning">
    <div class="header">
    <div class="fs70">
        <details>
            <summary>
            <b>Warning:</b> The following content is read from a public source that can be changed by anyone with the url.
            </summary>
{% if ctn.plain_url_mode %}
        Source-URL: <a href="{{ctn.src_url}}"><tt>{{ctn.src_url}}</tt></a><br>
        Encrypted source-URL: <a href="{% url 'md_preview_oburl' src_url=ctn.src_oburl %}"><tt>{{ctn.src_oburl|slice:":50"}}...</tt></a><br>
        (the link can be used to publish a read-only-version of a pad)

        <!--utc_md_rendering_plain_url:{{ctn.src_url}}-->
{% else %}
        Encrypted source-URL: <a href="{% url 'md_preview_oburl' src_url=ctn.src_oburl %}"><tt>{{ctn.src_oburl|slice:":50"}}...</tt></a><br>
        <!--utc_md_rendering_oburl:{{ctn.src_oburl}}-->
{% endif %}
        </details>
    </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="box_base box_top_content modest_links">

{{ctn.sanitized_html|safe}}

</div>

{% endblock %}

base/templates/base/static_page.html
{% extends "mainapp/base.html" %}
{% load extra_filters %}
{% load bleach_tags %}



{% block title %}{{ctn.title}}{% endblock %}



{% block content %}

<div class="box_base box_top_content modest_links">

{{ctn.src_txt|render_markdown|bleach}}

</div>

{% endblock %}